---

#### Version

  - name: Get version of installed slurm DEB
    shell: dpkg -l slurm|grep "^ii"|awk '{print $3}'|cut -d'-' -f1
    register: reg_slurm_yum_version
    check_mode: no
    changed_when: False

  - name: Get version of installed slurm DEB major version
    shell: dpkg -l slurm|grep "^ii"|awk '{print $3}'|cut -d'-' -f1|cut -d "." -f1-2|sed -e 's/\.//'
    register: reg_slurm_yum_version_major
    check_mode: no
    changed_when: False

  - name: Set fact with contents of fgci_slurmrepo_version with only the numbers
    set_fact: slurm_fact_fgci_slurmrepo_version="{{ fgci_slurmrepo_version | replace('fgcislurm', '')}}"

  - name: print custom facts in verbose mode
    debug: var=item verbosity=1
    with_items:
     - "{{ reg_slurm_yum_version['stdout'] }}"
     - "{{ slurm_fact_fgci_slurmrepo_version }}"
     - "{{ reg_slurm_yum_version_major['stdout'] }}"
